#pragma once

// 首次编译前请替换为你自己的 Wi-Fi 信息。
#define WIFI_PRIMARY_SSID "YOUR_PRIMARY_WIFI_SSID"
#define WIFI_PRIMARY_PASSWORD "YOUR_PRIMARY_WIFI_PASSWORD"
#define WIFI_FALLBACK_SSID "YOUR_FALLBACK_WIFI_SSID"
#define WIFI_FALLBACK_PASSWORD "YOUR_FALLBACK_WIFI_PASSWORD"
#define ROBOT_NAME "esp32-robot"
#define FIRMWARE_VERSION "0.1.0"
